#!/usr/bin/env bash

# Script that configures localhost and facebook.com IP resolution

echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
