#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine

# Utilise la commande 'ip' pour lister les adresses IPv4,
# puis 'awk' pour ne garder que l'adresse, et 'cut' pour enlever le masque (/xx).
ip -4 -o addr show | awk '{print $4}' | cut -d/ -f1
