#!/usr/bin/env bash
# Script that displays all active IPv4 IPs on the machine

# Utilise ifconfig pour lister les interfaces,
# grep pour trouver les lignes avec "inet" (les adresses IPv4),
# puis awk pour extraire la deuxième colonne (l'adresse IP),
# et sed pour supprimer le mot "addr:" si présent sur certaines distributions.
ifconfig | grep 'inet ' | awk '{print $2}' | sed 's/addr://'
